### PR TITLE
Fixed appearing vertical scroll bars in Chrome

### PR DESCRIPTION
**Pull request by Fusseldieb**
image
Even with sufficient space, scrollbars were appearing.

Removing `min-height` fixed that problem.

image

### CODE REVIEW

**Comment by Fusseldieb** [comment]
@euvl Yes, they still work like expected. 
image

**Comment by euvl** [comment]
Perfect 👍

**Comment by euvl** [comment]
yep, i didn't have enough time last weekend to check of nothing is broken by the change

**Comment by larsjanssen6** [comment]
@euvl I've tested it and it works 👍

**Pull request merged**
