### PR TITLE
Added property to set transition name on the overlay

### PR DESCRIPTION
**Pull request by pietromanneschi**

### CODE REVIEW

**Comment by euvl** [comment]
Thanks, but in docs you called it differently to the code

**Comment by pietromanneschi** [comment]
my bad. 
Sorry i am not so used to github pull requests yet. I've fixed the readme, how can i commit the change to THIS pull request? Or do i have to make another one?

**Comment by euvl** [comment]
You just have to commit in the same branch

**Comment by pietromanneschi** [comment]
Thank you, committed

**Pull request merged**
