### PR TITLE
Fixes #15 #60

### LINKED ISSUE #15: Event "opened"
I'm trying to set the focus on an element once the modal is opened. However, the $refs item is undefined after the 'opened' event is emitted. I set a breakpoint and saw that the modal wasn't visible before the emit was emitted:

event

Relevant code:

```
<modal name="addContactModal" @opened="opened">
<input type="text" ref="focus"/>
```

```
opened (event) {
  this.$refs.focus.focus();
},
```

Do you have an idea?

### PR DESCRIPTION
**Pull request by DaxChen**
# Fix opened event $refs.modal undefined
#15 
moved after events `'opened'` and `'closed'` to watch.visible (`callAfterEvent` method inside setTimeout and $nextTick), so async DOM changes are done and `$refs.modal` won't be `undefined` in `'opened'`

See the `opened` event's `console.log` in demo `SizeModal.vue` **Demo: Width: 60%, Height: auto**

# Fix position.top when height 'auto'
#60 
when height 'auto', `trueModalHeight` now returns the _true_ rendered height.

`modal.renderedHeight` is calculated in method `updateRenderedHeight` by calling `getBoundingClientRect`. This is updated once in 'opened', and I used a MutationObserver to detect DOM changes to children of modal, so the height will be auto updated when content changes. 

See demo `SizeModal.vue` **Demo: Width: 60%, Height: auto**
The modal will be positioned vertically centered, and when it's higher then the screen, `position.top` will be `0`

### CODE REVIEW

**Comment by DaxChen** [comment]
Hi @euvl,
I tried to fix some issues with these proposed approach, can you look at it and see if these implementations (such as `getBoundingClientRect` and `MutationObserver`) are okay for this library?
I'm happy to change any part if you find non appropriate!

Thanks!
Dax

**Comment by euvl** [comment]
Wow, nice! 😮 
Good job @DaxChen! I will review the PR on these weekends! 
Also thanks a lot for extending demos for testing, high five for that! 👍 👍 👍

**Comment by euvl** [comment]
Hey @DaxChen, 

I've merged your changes to master, great PR! I didn't even know about existence of MutationObserver 😄 

I will do a bit more testing before publishing but it is all good.
Thanks a lot for your PR! 😄 👍 👍 👍

**Comment by DaxChen** [comment]
My pleasure! Thank you for the awesome library! 👍 👍 👍

**Pull request merged**
