### PR TITLE
[Fix] add attributes:true to MutationObserver

### PR DESCRIPTION
**Pull request by DaxChen**
Hi @euvl!

After some more more testing, I found that `attributes: true` param is needed in `MutationObserver` (as some cases the Modal's `height` changes because of attributes)

Thank you so much!!

### CODE REVIEW

**Comment by euvl** [comment]
Cool, thanks! Soz, I didnt have time yet to test everything. Will do asap 👍

**Comment by DaxChen** [comment]
Ahh @euvl  I found a bug recently!! before you publish, can I push one more commit?

**Comment by euvl** [comment]
Hey @DaxChen, don't worry, its all good. I've just merged and published, but feel free to open a new PR 👍 😄

**Comment by euvl** [comment]
Also I did a tiny refactoring when had time, so yu will still have to checkout latest master

**Pull request merged**
