### PR TITLE
Account for window scroll when dragging and positioning modal

### PR DESCRIPTION
**Pull request by brizzo**
Modal positioning did not account for window scroll amount. Ensure the
modal is positioned in and bound by the window viewport after
scrolling and while dragging.

### CODE REVIEW

**Comment by euvl** [comment]
Hey @brizzo, is this for dragging scrollable modals?

**Comment by cypressnorthdev** [comment]
@euvl, no, this is in regards to the position of the modal in a browser window after the browser was scrolled. Assuming you have a draggable modal (not necessarily scrollable), if you open the modal, then close it, and then scroll the browser window, then reopen the modal, the position and draggable area are relative to the browser window before it was scrolled. This limits the draggable area for the modal, i.e. the modal can’t be dragged to the bottom of the window anymore. This fix attempts to correct that by accounting for window scroll.

**Comment by brizzo** [comment]
@euvl, no, this is in regards to the position of the modal in a browser window after the browser was scrolled. Assuming you have a draggable modal (not necessarily scrollable), if you open the modal, then close it, and then scroll the browser window, then reopen the modal, the position and draggable area are relative to the browser window before it was scrolled. This limits the draggable area for the modal, i.e. the modal can’t be dragged to the bottom of the window anymore. This fix attempts to correct that by accounting for window scroll.

**Comment by cypressnorthdev** [comment]
@euvl, after further investigation and some trial and error, I've discovered that the issue I've described above is not related to window scrolling calculations.

I've been rendering my modals into a parent div that has a transform applied to it. If I remove the transform, or render the modal elsewhere, the draggable behavior behaves as expected.

Needless to say, this pull request is no longer necessary. However I do believe there is an issue with draggable modals rendered under an element with a transform applied. In my particular case, `transform: translateX(0%);` was the offending style. Removing this from the parent element fixed the issue.

**Comment by brizzo** [comment]
@euvl, after further investigation and some trial and error, I've discovered that the issue I've described above is not related to window scrolling calculations.

I've been rendering my modals into a parent div that has a transform applied to it. If I remove the transform, or render the modal elsewhere, the draggable behavior behaves as expected.

Needless to say, this pull request is no longer necessary. However I do believe there is an issue with draggable modals rendered under an element with a transform applied. In my particular case, transform: translateX(0%); was the offending style. Removing this from the parent element fixed the issue.

**Pull request closed without merging**
