### PR TITLE
Fix MutationObserver callback $refs.modal undefined

### PR DESCRIPTION
**Pull request by DaxChen**
Because mutation observer callback fires whenever the DOM changes, so when the Modal closes, the callback also fires with $refs.modal undefined.

Added a check in the callback.

Great thanks!!

### CODE REVIEW

**Comment by DaxChen** [comment]
I merged your branch into this PR, not sure if a rebuild is needed...

**Comment by euvl** [comment]
No worries, I will rebuild it 👍

**Comment by euvl** [comment]
Published in 1.3.3

**Comment by DaxChen** [comment]
WOW @euvl you're the best!!!

**Pull request merged**
