### PR TITLE
added rtl support

### PR DESCRIPTION
**Pull request by miladr**
Contains a simple hack for supporting RTL languages such as Persian and Arabic.

### CODE REVIEW

**Comment by euvl** [comment]
Hey, thanks for your PR. 
Could you please make sure that draggable and resizable features are not broken by this pr.
Also I think direction can easily be `computed` value.

Thanks 👍

**Comment by miladr** [comment]
I will ASAP.

**Comment by acrolink** [comment]
Seems that this library still does not support RTL web applications. At the meantime I have found this CSS code to solve the issue:

```
.v--modal-overlay {
    direction: ltr;
}
```

**Comment by euvl** [comment]
The author of the PR never came back. Also from your post seems that it's not that hard to do in-app itself (3 lines ±? )

**Pull request closed without merging**
