### PR TITLE
Set width and height props reactive

### LINKED ISSUE #141: The modal width prop is not reactive
Hi,

First of all, thanks for the awesome work.

I got an issue where I try to modify the modal `width` parameter after it has been mounted.

I have a wrapper component on the actual modal where I have a `width` data property. I pass this property on the modal component. I would expect that anytime the width prop changes on the wrapper, to be picked up by the modal as well, and trigger a resize.

My wrapper component in short:

    <template>
        <v-modal :name="name" :width="width">
            <slot></slot>
        </v-modal>
    </template>

    <script>

    export default {
        props: {
            name: {
                type: String,
                required: true
            }
        },

        data() {
            return {
                width: "45%",
          
            }
        },

        methods: {
          
            opened(event) {
                this.resizeHandler()
                window.addEventListener('resize', _.debounce(this.resizeHandler, 50))
                this.$emit('modal-opened', event)
            },

            beforeClose(event) {
                window.removeEventListener('resize', _.debounce(this.resizeHandler, 50))
                this.$emit('before-close', event)
            },

            resizeHandler() {
              
                if ($(window).width() <= App.getResponsiveBreakpoint('sm')) {
                    this.width = '100%'
                }
                if ($(window).width() > App.getResponsiveBreakpoint('sm') && $(window).width() <= App.getResponsiveBreakpoint('md')) {
                    this.width = '65%'
                }
                if ($(window).width() > App.getResponsiveBreakpoint('md')) {
                    this.width = '45%'
                }
            }
        },
    }

    </script> 

Maybe something I'm doing wrong?

Thanks in advance!

### PR DESCRIPTION
**Pull request by VitorLuizC**
I've renamed `setInitialSize` to `setSize` and just call it on `width` and `height` watchers.

Fixes #141 and #369.

### CODE REVIEW

**Comment by larsjanssen6** [comment]
@VitorLuizC that's great! I need this 👍

**Comment by zippos** [comment]
Cool. Just looking for it. :)

**Comment by VitorLuizC** [comment]
@euvl can you check this PR? The stale bot will close it.

**Comment by euvl** [comment]
Hey, found some issues with dragging, i will write down the findings whenever i have a free minute. otherwise please test with other features enabled.

thanks

**Pull request closed without merging**
